# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    #span:
      #line_numbers: false
    #block:
      #line_numbers: true
      #start_line: 1

plugins:
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-octicons
    - jemoji
    - jekyll-seo-tag
    - jekyll-archives
    - jekyll-toc
    - jekyll-email-protect
    - jekyll/tagging
    - jekyll-tagging-related_posts


paginate: 5
paginate_path: "/blog/page/:num/"
comments: true

excerpt_separator: "<!-- more -->"

toc:
  min_level: 1 # default: 1
  max_level: 5 # default: 6

#jekyll-archives:
 # enabled:
#      - tags
#      - categories
  #layout: 'archive'
  #layouts:
    #tag: tags
    #category: category
  #permalinks:
    #tag: '/tag/:name'
    #category: '/category/:name'

tag_page_layout: tags
tag_page_dir: tag

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Clarissa Podell
description: "Clarissa Podell's Personal Site and Blog"
keywords: "Jekyll, theme, free, download, SEO, blog, web, computer security"
url: http://localhost:4000/testgitpages  #http://yourdomain.com
baseurl: "/testgitpages"

#google_analytics: UA-121634252-1
repo: http://github.com/c1arissa/testgitpages
#disqus_shortname: "nandothemes"
#disqus_site_shortname: "nandothemes"

tag_page: "/testgitpages/tags/"
category_page: "/testgitpages/categories/"

# Author settings
author:
  name: Clarissa Podell
  job: Cybersecurity and Hacking enthusiast
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb: /images/profile.jpg
  email: clarissapodell@gmail.com
  url: https://c1arissa.github.io/
  github: https://github.com/c1arissa
  mobile: (631)-708-2725
  #twitter: https://twitter.com/umdevux
  #facebook: https://facebook.com/umdevux
  linkedin: https://linkedin.com/in/clarissapodell

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog
  - slug: links
    title: Links
  - slug: tags
    title: Tags
  - slug: contact
    title: Contact

whitelist:
    - jekyll-redirect-from

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
