# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
#plugins: [jekyll-paginate]

plugins:
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-octicons

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Clarissa Podell
description: "Clarissa Podell's personal website and blog."
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://c1arissa.github.io
baseurl: "/testgitpages"

google_analytics: UA-52446115-1
repo: http://github.com/c1arissa/testgitpages
#disqus_shortname: "nandothemes"
#disqus_site_shortname: "nandothemes"

# Author settings
author:
  name: Clarissa Podell
  job: Computer Security and Hacking enthusiast
  bio: "Enthusiast performance, responsive design and usability, always looking for the best project and good coffee."
  thumb: /images/profile.jpg
  email: clarissapodell@gmail.com
  url: https://c1arissa.github.io/
  github: https://github.com/c1arissa
  #twitter: https://twitter.com/umdevux
  #facebook: https://facebook.com/umdevux
  linkedin: https://linkedin.com/in/clarissapodell

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog
  - slug: links
    title: Links
  - slug: tags
    title: Tags
  - slug: contact
    title: Contact

whitelist:
    - jekyll-redirect-from

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
